---
- name: Install the latest version of chrony
  yum: name=chrony state=latest

- name: Copy chrony.conf.j2 to /etc/chrony.conf
  template: src=chrony.conf.j2 dest=/etc/chrony.conf mode=0644 owner=root group=root

- name: Add chronyd to systemd 
  systemd: name=chronyd state=started enabled=yes masked=no
