---

 - name: create dir /etc/kubernetes/pki/controller-manager 
   file: path=/etc/kubernetes/pki/{{ item }} state=directory mode=0755
   loop:
     - controller-manager

 - name: Download rootca.crt and rootca.key
   get_url:
     url: http://{{ groups['fileserver'] | join('') }}/kubernetes/pki/rootca/{{ item }}
     dest: /etc/kubernetes/pki/rootca/{{item}}
   loop:
     - rootca.crt
     - rootca.key


 - name: generate controller manager private key
   openssl_privatekey: path=/etc/kubernetes/pki/controller-manager/controller-manager.key

 - name: Generate an OpenSSL Certificate Signing Request controller-mananager.csr
   openssl_csr:
     path: /etc/kubernetes/pki/controller-manager/controller-manager.csr
     privatekey_path: /etc/kubernetes/pki/controller-manager/controller-manager.key
     country_name: CN
     state_or_province_name: Beijing
     organization_name: Cloud
     organizational_unit_name: Development
     common_name: "system:kube-controller-manager"
 
 - name: Generate controller-manager.crt
   openssl_certificate:
     path: /etc/kubernetes/pki/controller-manager/controller-manager.crt
     csr_path: /etc/kubernetes/pki/controller-manager/controller-manager.csr
     ownca_path: /etc/kubernetes/pki/rootca/rootca.crt
     ownca_privatekey_path: /etc/kubernetes/pki/rootca/rootca.key
     ownca_not_before: "{{ certs_start }}Z"
     ownca_not_after: "{{ certs_end }}Z"
     provider: ownca

