---
 - name: create dir /etc/kubernetes/pki 
   file: path=/etc/kubernetes/pki/{{ item }} state=directory mode=0755
   loop:
     - rootca
     - etcd

 - name: Download rootca.crt and rootca.key
   get_url:
     url: http://{{ groups['fileserver'] | join('') }}/kubernetes/pki/rootca/{{ item }}
     dest: /etc/kubernetes/pki/rootca
   loop:
     - rootca.crt
     - rootca.key


 - name: generate etcd service and peer private key
   openssl_privatekey: path=/etc/kubernetes/pki/etcd/{{item}}
   loop:
     - etcd.key
     - peer.key

 - name: Generate an OpenSSL Certificate Signing Request etcd.csr and peer.csr
   openssl_csr:
     path: /etc/kubernetes/pki/etcd/{{item}}.csr
     privatekey_path: /etc/kubernetes/pki/etcd/{{item}}.key
     country_name: CN
     state_or_province_name: Beijing
     organization_name: Cloud
     organizational_unit_name: Development
     common_name: "{{ ansible_fqdn }}"
     subject_alt_name: ["IP:127.0.0.1","IP:{{ inventory_hostname }}","DNS:{{ ansible_fqdn }}"]
   loop:
     - etcd
     - peer

 - name: Generate an OpenSSL certificate  etcd.crt and peer.crt signed with your own CA certificate
   openssl_certificate:
     path: /etc/kubernetes/pki/etcd/{{item}}.crt
     csr_path: /etc/kubernetes/pki/etcd/{{item}}.csr
     ownca_path: /etc/kubernetes/pki/rootca/rootca.crt
     ownca_privatekey_path: /etc/kubernetes/pki/rootca/rootca.key
     ownca_not_before: "{{ certs_start }}Z"
     ownca_not_after: "{{ certs_end }}Z"
     provider: ownca
   loop:
     - etcd
     - peer
