---
- name: Install software http
  yum: name=httpd state=present

- name: start http service
  systemd: name=httpd state=restarted enabled=yes masked=no

- name: configure  firewalld policy for httpd
  firewalld: port={{ item }} permanent=true state=enabled immediate=true
  loop:
    - 80/tcp
