---
- name: step1 create kubeconfig file scheduler.conf  for kube-scheduler
  shell: kubectl config --kubeconfig=/etc/kubernetes/scheduler.conf set-cluster default-cluster --server=https://{{ cluster_vip }}:6443 --certificate-authority /etc/kubernetes/pki/rootca/rootca.crt --embed-certs 

- name: step2 create kubeconfig file scheduler.conf  for kube-scheduler
  shell: kubectl config --kubeconfig=/etc/kubernetes/scheduler.conf set-credentials default-manager --client-key /etc/kubernetes/pki/scheduler/scheduler.key --client-certificate /etc/kubernetes/pki/scheduler/scheduler.crt --embed-certs 

- name: step3 create kubeconfig file scheduler.conf  for kube-scheduler
  shell: kubectl config --kubeconfig=/etc/kubernetes/scheduler.conf set-context default-system --cluster default-cluster --user default-manager

- name: step4 create kubeconfig file scheduler.conf  for kube-scheduler
  shell: kubectl config --kubeconfig=/etc/kubernetes/scheduler.conf use-context default-system

- name: copy file kube-scheduler.yaml.j2 to /etc/kubernetes/manifests/kube-schedule.yaml
  template: src=kube-scheduler.yaml.j2 dest=/etc/kubernetes/manifests/kube-scheduler.yaml owner=root group=root mode=0600
