---
- name: copy file kube-apiserver.yaml.j2 to /etc/kubernetes/manifests/kube-apiserver.yaml
  template: src=kube-apiserver.yaml.j2 dest=/etc/kubernetes/manifests/kube-apiserver.yaml owner=root group=root mode=0600
